ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.realty.ApplicationKt.module ]
    }
}

database {
    url = "jdbc:postgresql://127.0.1.14:5432/postgres?currentSchema=android"
    driver = "org.postgresql.Driver"
    user = "postgres"
    password = "admin"
    maxPoolSize = 10
}

jwt {
    secret = "realty-super-secret-key-change-in-production-min-256-bits"
    issuer = "realty-app"
    audience = "realty-users"
    accessTokenExpiryMs = 3600000
    refreshTokenExpiryDays = 30
}
